semantic_models:
  - name: products
    defaults:
      agg_time_dimension: sell_start_date
    description: This table is at the products grain with one row per product
    model: ref('products')
    entities:
      - name: product
        type: primary
        expr: product_key
    dimensions:
      - name: product_name
        type: categorical
      - name: product_subcategory
        type: categorical
      - name: product_category
        type: categorical
      - name: sell_start_date
        type: time
        type_params: 
          time_granularity: day
      - name: sell_end_date
        type: time
        type_params:
          time_granularity: day